server:
  port: 8080
  servlet:
    context-path: /rabbitmq-provider
spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 虚拟host 可以不设置,使用server默认host
    virtual-host: /
    #消息确认配置项
    # 开启发送确认；确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    # 开启发送失败退回；确认消息已发送到队列(Queue)
    publisher-returns: true
